import SwiftUI

// All color tokens are defined in Assets.xcassets and auto-generated by Xcode.
// Access them as: Color.backgroundPrimary, Color.surfaceBase, Color.appPrimary, etc.
// No manual Color extension needed — Xcode generates properties from colorset names.
