default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :deploy do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    setup_ci

    match(
      type: "appstore",
      readonly: true,
      app_identifier: "com.xrcc.retrace.ios.v1"
    )

    update_code_signing_settings(
      path: "CameraAccess.xcodeproj",
      use_automatic_signing: false,
      team_id: "V56DG94ZL5",
      bundle_identifier: "com.xrcc.retrace.ios.v1",
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.xrcc.retrace.ios.v1",
      targets: ["CameraAccess"]
    )

    increment_build_number(
      build_number: latest_testflight_build_number(
        app_identifier: "com.xrcc.retrace.ios.v1"
      ) + 1,
      xcodeproj: "CameraAccess.xcodeproj"
    )

    build_app(
      project: "CameraAccess.xcodeproj",
      scheme: "CameraAccess",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "com.xrcc.retrace.ios.v1" => "match AppStore com.xrcc.retrace.ios.v1"
        }
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
